<a href="https://colab.research.google.com/github/newmantic/lu_decomposition/blob/main/lu_decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def lu_decomposition(A):
    """
    Perform LU decomposition of a matrix A using Doolittle's method.

    Parameters:
    A (np.ndarray): The input matrix of shape (n, n).

    Returns:
    tuple: L (np.ndarray), U (np.ndarray) where A = L * U.
    """
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for i in range(n):
        # Upper triangular matrix U
        for k in range(i, n):
            sum_u = sum(L[i][j] * U[j][k] for j in range(i))
            U[i][k] = A[i][k] - sum_u

        # Lower triangular matrix L
        for k in range(i, n):
            if i == k:
                L[i][i] = 1  # Diagonal as 1
            else:
                sum_l = sum(L[k][j] * U[j][i] for j in range(i))
                L[k][i] = (A[k][i] - sum_l) / U[i][i]

    return L, U

# Testable example:
A = np.array([[2, -1, -2],
              [-4, 6, 3],
              [-4, -2, 8]])

L, U = lu_decomposition(A)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)

# Verify that A = L * U
A_reconstructed = np.dot(L, U)
print("Reconstructed Matrix A:")
print(A_reconstructed)

Matrix L:
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-2. -1.  1.]]
Matrix U:
[[ 2. -1. -2.]
 [ 0.  4. -1.]
 [ 0.  0.  3.]]
Reconstructed Matrix A:
[[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]


In [2]:
# example:
A_advanced = np.array([[4, 3, 2],
                       [6, 3, 2],
                       [2, 1, 3]])

L_advanced, U_advanced = lu_decomposition(A_advanced)
print("Advanced Matrix L:")
print(L_advanced)
print("Advanced Matrix U:")
print(U_advanced)

# Verify that A_advanced = L_advanced * U_advanced
A_advanced_reconstructed = np.dot(L_advanced, U_advanced)
print("Reconstructed Advanced Matrix A:")
print(A_advanced_reconstructed)

Advanced Matrix L:
[[1.         0.         0.        ]
 [1.5        1.         0.        ]
 [0.5        0.33333333 1.        ]]
Advanced Matrix U:
[[ 4.          3.          2.        ]
 [ 0.         -1.5        -1.        ]
 [ 0.          0.          2.33333333]]
Reconstructed Advanced Matrix A:
[[4. 3. 2.]
 [6. 3. 2.]
 [2. 1. 3.]]
